
spring:
  h2:
    console:
      enabled: true
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
  datasource:
    hikari.jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
    hikari.username: sa

naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
  client:
    id: Dcph364ZdWxMAJyS1pbW
    secret: dEhmia0Vkl